#!/bin/bash

echo 0 > /proc/sys/kernel/yama/ptrace_scope

/usr/bin/shellinaboxd -p 80 -u webshell -g webshell --disable-ssl --no-beep --debug --service /:${USER}:${USER}:${PWD}:bash --user-css 'Black on White:+/etc/shellinabox/options-enabled/00+Black on White.css,White On Black:-/etc/shellinabox/options-enabled/00_White On Black.css;Color Terminal:+/etc/shellinabox/options-enabled/01+Color Terminal.css,Monochrome:-/etc/shellinabox/options-enabled/01_Monochrome.css'